import json
import networkx as nx
from config import logger

class SchemaManager:
    def __init__(self, schema_file: str, dialect: str = "Oracle", target_schema: str = None):
        self.schema_file = schema_file
        self.dialect = dialect
        self.target_schema = target_schema
        self.schema_data = self._load_schema()
        self.dag = self._build_dag()

    def _fqn(self, table_name: str) -> str:
        if self.target_schema:
            return f"{self.target_schema}.{table_name.upper()}"
        return table_name.upper()

    def _load_schema(self) -> dict:
        with open(self.schema_file, 'r') as f:
            return json.load(f)

    def _build_dag(self) -> nx.DiGraph:
        """
        Builds a Directed Acyclic Graph (DAG) where nodes are tables
        and edges represent foreign key dependencies.
        """
        dag = nx.DiGraph()
        for table in self.schema_data.get('tables', []):
            table_name = table['name'].upper()
            dag.add_node(table_name, **table)

            for fk in table.get('foreign_keys', []):
                ref_table = fk['references_table'].upper()
                # Edge from parent to child means parent must come before child
                dag.add_edge(ref_table, table_name) 

        if not nx.is_directed_acyclic_graph(dag):
            raise ValueError("Schema contains cyclic foreign key dependencies!")
        return dag

    def get_creation_order(self) -> list[str]:
        """Returns table names in topological order (parents first)."""
        return list(nx.topological_sort(self.dag))

    def get_drop_order(self) -> list[str]:
        """Returns table names in reverse topological order (children first)."""
        return list(reversed(self.get_creation_order()))

    def get_table_schema(self, table_name: str) -> dict:
        return self.dag.nodes[table_name.upper()]

    def generate_drop_ddl(self, table_name: str) -> str:
        fqn = self._fqn(table_name)
        if self.dialect == "PostgreSQL":
            return f"DROP TABLE IF EXISTS {fqn} CASCADE"
        elif self.dialect == "MSSQL":
            return f"IF OBJECT_ID('{fqn}', 'U') IS NOT NULL DROP TABLE {fqn}"
        else:
            return f"DROP TABLE {fqn} CASCADE CONSTRAINTS"

    def generate_create_ddl(self, table_name: str) -> str:
        table_def = self.get_table_schema(table_name)
        columns_ddl = []
        inline_pk_cols = []
        
        import re
        for col in table_def['columns']:
            type_str = col['type']
            
            if col.get('primary_key', False) or 'PRIMARY KEY' in type_str.upper():
                inline_pk_cols.append(col['name'])
                
            # Strip inline PRIMARY KEY to prevent ORA-02260 since we handle it at the table level
            type_str = re.sub(r'(?i)\bPRIMARY\s+KEY\b', '', type_str).strip()
            
            if col.get('auto_generated', False):
                # Clean cross-dialect identity pollution
                clean_type = re.sub(r'(?i)\bGENERATED\s+(BY\s+DEFAULT\s+)?AS\s+IDENTITY\b', '', type_str)
                clean_type = re.sub(r'(?i)\bIDENTITY\s*\(\d+,\d+\)', '', clean_type)
                clean_type = re.sub(r'(?i)\bIDENTITY\b', '', clean_type)
                clean_type = re.sub(r'(?i)\bSERIAL\b', '', clean_type).strip()
                
                parts = clean_type.split(' ', 1)
                datatype = parts[0] if parts[0] else "INT"
                rest = parts[1] if len(parts) > 1 else ""
                
                # Check for appropriate identity syntax based on dialect
                if self.dialect == "PostgreSQL":
                    col_ddl = f"{col['name']} SERIAL {rest}".strip()
                elif self.dialect == "MSSQL":
                    if datatype.upper() == 'NUMBER': datatype = 'INT'
                    col_ddl = f"{col['name']} {datatype} IDENTITY(1,1) {rest}".strip()
                else: # Oracle
                    if datatype.upper() == 'INT': datatype = 'NUMBER'
                    col_ddl = f"{col['name']} {datatype} GENERATED BY DEFAULT AS IDENTITY {rest}".strip()
            else:
                col_ddl = f"{col['name']} {type_str}"
                
            columns_ddl.append(col_ddl)
            
        pk_cols_list = table_def.get('primary_key_columns', [])
        if not pk_cols_list:
            pk_cols_list = inline_pk_cols
            
        if pk_cols_list:
            pk_cols = ", ".join(pk_cols_list)
            pk_name = f"PK_{table_name.upper()}"[:30]
            columns_ddl.append(f"CONSTRAINT {pk_name} PRIMARY KEY ({pk_cols})")
            
        columns_str = ",\n    ".join(columns_ddl)
        fqn = self._fqn(table_name)
        ddl = f"CREATE TABLE {fqn} (\n    {columns_str}\n)"
        return ddl
        
    def generate_fk_ddl(self, table_name: str) -> list[str]:
        table_def = self.get_table_schema(table_name)
        fk_ddls = []
        for i, fk in enumerate(table_def.get('foreign_keys', [])):
            fk_col = fk.get('column')
            if not fk_col and fk.get('columns'): fk_col = fk.get('columns')[0]
            
            ref_col = fk.get('references_column')
            if not ref_col and fk.get('references_columns'): ref_col = fk.get('references_columns')[0]
            
            if not fk_col or not ref_col: continue
            
            prefix = f"{self.target_schema}_" if self.target_schema else ""
            fk_name = f"FK_{prefix}{table_name}_{fk_col}_{i}".upper()
            if self.dialect == "Oracle":
                # Strip prefix since it's not needed for Oracle uniqueness and wastes precious chars
                fk_name = f"FK_{table_name}_{fk_col}_{i}".upper()
                fk_name = fk_name[:30]
            else:
                if len(fk_name) > 128:
                    fk_name = f"{fk_name[:120]}_{i}"
                
            fqn = self._fqn(table_name)
            ref_fqn = self._fqn(fk['references_table'])
            ddl = (f"ALTER TABLE {fqn} "
                   f"ADD CONSTRAINT {fk_name} "
                   f"FOREIGN KEY ({fk_col}) "
                   f"REFERENCES {ref_fqn}({ref_col})")
            fk_ddls.append(ddl)
        return fk_ddls

    def generate_index_ddl(self, table_name: str) -> list[str]:
        table_def = self.get_table_schema(table_name)
        idx_ddls = []
        for i, idx in enumerate(table_def.get('indexes', [])):
            idx_cols = ", ".join(idx['columns'])
            safe_cols = "_".join(idx['columns']).replace(" ", "")
            prefix = f"{self.target_schema}_" if self.target_schema else ""
            
            idx_name = f"IDX_{prefix}{table_name}_{safe_cols}_{i}".upper()
            if self.dialect == "Oracle":
                idx_name = f"IDX_{table_name}_{safe_cols}".upper()
                idx_name = f"{idx_name[:26]}_{i}"
            else:
                if len(idx_name) > 128:
                    idx_name = f"{idx_name[:120]}_{i}"
            
            fqn = self._fqn(table_name)
            ddl = f"CREATE INDEX {idx_name} ON {fqn} ({idx_cols})"
            idx_ddls.append(ddl)
        return idx_ddls

    def read_plsql_file(self, file_path: str) -> str:
        with open(file_path, 'r') as f:
            content = f.read()
        return content.strip().rstrip('/').strip()

    def get_procedures(self) -> list[dict]:
        return self.schema_data.get('procedures', [])

    def get_functions(self) -> list[dict]:
        return self.schema_data.get('functions', [])

    def get_triggers(self) -> list[dict]:
        return self.schema_data.get('triggers', [])
