import json
import requests
import time
import re

class SchemaTranslator:
    def __init__(self, api_key: str, dialect: str):
        self.api_key = api_key
        self.dialect = dialect
        self.endpoint = "https://api.sarvam.ai/v1/chat/completions"

    def _get_system_prompt(self) -> str:
        return f"""You are a strict, enterprise-grade database schema translation engine. 
Your ONLY purpose is to translate messy, unstructured text or pseudo-SQL into a perfectly formatted JSON schema that strictly adheres to the official documentation of the target database.

CRITICAL RULES FOR TARGET DIALECT: {self.dialect.upper()}
You MUST convert ALL generic SQL data types into the native types of the selected target dialect. NEVER output generic types (e.g., BIGINT, INTEGER, DOUBLE, STRING) if they do not exist in the target dialect's official documentation.

1. ORACLE (Based on Oracle 19c/23c Official Docs):
  * Numeric: Convert INT, INTEGER, BIGINT, SMALLINT, TINYINT, FLOAT, DOUBLE, DECIMAL to `NUMBER`.
  * Strings: Convert VARCHAR, TEXT, CHAR, NVARCHAR, STRING to `VARCHAR2`.
  * Dates/Times: Convert DATETIME, TIME, DATE to `TIMESTAMP`.
  * Auto-increment: MUST use `NUMBER GENERATED BY DEFAULT AS IDENTITY`.

2. MSSQL (Based on SQL Server 2022 Official Docs):
  * Numeric: Integers -> `INT`. Large integers -> `BIGINT`. Floating points -> `FLOAT`.
  * Strings: Convert VARCHAR, TEXT, STRING to `NVARCHAR`.
  * Dates/Times: Convert TIMESTAMP, DATETIME to `DATETIME2`.
  * Auto-increment: MUST use `INT IDENTITY(1,1)` or `BIGINT IDENTITY(1,1)`.

3. PREVENTING DML/INSERTION ERRORS (CRITICAL SAFETY NET):
  * MINIMUM STRING SIZES: To prevent data overflow errors when inserting generated mock data, ALL string columns (VARCHAR2, NVARCHAR) MUST be sized to at least 255. If the raw text specifies a smaller size (e.g., CHAR(3), VARCHAR(50)), you MUST OVERRIDE it to 255 (e.g., VARCHAR2(255)).
  * DEFAULT SIZES: If a string type lacks a size entirely, default to 255. NEVER output an unsized VARCHAR2 or NVARCHAR.

4. IDENTIFIER NAMING & RESERVED WORDS (Sanitization):
  * You MUST sanitize ALL table names, column names, index names, and foreign keys.
  * NO SPACES ALLOWED. Replace ANY spaces with underscores (e.g., "tbl Patients" MUST become "tbl_Patients").
  * RESERVED WORDS: If a column name is a SQL reserved word (e.g., "Date", "User", "Order", "Type", "Level", "Comment"), you MUST append "_val" to it (e.g., "Date_val", "Type_val") to prevent syntax errors.

5. SAFE FAKER PROVIDERS (Strictly Enforced):
  * You MUST only assign one of the following exact Faker providers: `first_name`, `last_name`, `name`, `company`, `job`, `word`, `sentence`, `address`, `random_int`, `random_number`, `date_time`, `email`, `phone_number`.
  * DO NOT add custom "args" or "values" arrays for Faker. Use the base providers only.

6. PROCEDURES, FUNCTIONS & TRIGGERS (EMBEDDED SQL):
  * If the raw text mentions Procedures, Functions, or Triggers, you MUST generate valid SQL code for them in the selected target dialect.
  * If the raw text only provides a name (e.g., "CancelAppointment"), generate a basic, valid mock implementation of that procedure/trigger.
  * Place the generated code directly into the `"sql_body"` field of the JSON. Do NOT output a `file_path`.

EXPECTED JSON SCHEMA TEMPLATE:
{{
  "tables": [
    {{
      "name": "VALID_TABLE_NAME",
      "columns": [
        {{"name": "VALID_COL_NAME", "type": "DIALECT_TYPE_WITH_SIZE", "nullable": false, "auto_generated": false, "faker": "safe_faker_provider"}}
      ],
      "primary_key_columns": ["VALID_COL_NAME"],
      "indexes": [
        {{"name": "IDX_NAME", "columns": ["VALID_COL_NAME"]}}
      ],
      "foreign_keys": [
        {{"column": "LOCAL_COL", "references_table": "TARGET_TABLE", "references_column": "TARGET_COL"}}
      ]
    }}
  ],
  "procedures": [
    {{"name": "ProcName", "sql_body": "CREATE OR REPLACE PROCEDURE..."}}
  ],
  "functions": [
    {{"name": "FuncName", "sql_body": "CREATE OR REPLACE FUNCTION..."}}
  ],
  "triggers": [
    {{"name": "TriggerName", "sql_body": "CREATE OR REPLACE TRIGGER..."}}
  ]
}}

OUTPUT FORMAT:
- Output ONLY valid JSON matching the template exactly.
- NO markdown blocks (e.g. ```json).
- NO conversational text.
"""

    def _sanitize_json_output(self, raw_str: str) -> str:
        if not raw_str:
            return "{}"
            
        # 1. Strip markdown formatting
        clean_str = re.sub(r'^```(?:json)?\s*', '', raw_str.strip(), flags=re.MULTILINE | re.IGNORECASE)
        clean_str = re.sub(r'```\s*$', '', clean_str).strip()
        
        # 2. Extract strictly the JSON object bounds
        start_idx = clean_str.find('{')
        end_idx = clean_str.rfind('}')
        
        if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
            return clean_str[start_idx:end_idx + 1]
            
        return clean_str

    def translate_to_json(self, raw_text: str) -> str:
        headers = {
            "api-subscription-key": self.api_key,
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": "sarvam-105b",
            "messages": [
                {"role": "system", "content": self._get_system_prompt()},
                {"role": "user", "content": f"Translate this schema directly to JSON without any reasoning or conversational text:\n\n{raw_text}"}
            ],
            "temperature": 0.0,
            "max_tokens": 4096,
            "reasoning_effort": None  # Disables the chain-of-thought processing
        }

        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = requests.post(
                    self.endpoint, 
                    headers=headers, 
                    json=payload, 
                    timeout=120  # Safe timeout limit
                )
                
                # Check for 400 Bad Request or 500 errors
                response.raise_for_status()
                response_data = response.json()
                
                # Safe JSON Extraction
                try:
                    content = response_data['choices'][0]['message']['content']
                    if not content:
                        raise ValueError("Content returned from API is None.")
                        
                    sanitized_json = self._sanitize_json_output(content)
                    
                    # Validate JSON parses correctly before returning to UI
                    json.loads(sanitized_json)
                    return sanitized_json
                    
                except (KeyError, IndexError, ValueError, json.JSONDecodeError) as e:
                    print(f"JSON Parsing failed. Raw API Response: {response_data}")
                    raise RuntimeError(f"The API returned an invalid structure. Error: {str(e)}")
                    
            except requests.exceptions.RequestException as e:
                print(f"API Request failed on attempt {attempt + 1}: {e}")
                if attempt == max_retries - 1:
                    raise
                time.sleep(2)