import json
import requests
import time
import re

class SchemaTranslator:
    def __init__(self, api_key: str, dialect: str):
        self.api_key = api_key
        self.dialect = dialect
        self.endpoint = "https://api.sarvam.ai/v1/chat/completions"

    def _get_system_prompt(self) -> str:
        return f"""You are a strict, enterprise-grade database schema translation engine. 
Your ONLY purpose is to translate messy, unstructured text or pseudo-SQL into a perfectly formatted JSON schema that strictly adheres to the official documentation of the target database.

CRITICAL RULES FOR TARGET DIALECT: {self.dialect.upper()}
You MUST completely ignore the rules of the non-selected dialect. DO NOT mix Oracle and MSSQL data types.

1. ORACLE (Based on Oracle 19c/23c Official Docs):
  * Numeric: Convert INT, INTEGER, BIGINT, SMALLINT, TINYINT, FLOAT, DOUBLE to `NUMBER`.
  * Decimal: Convert DECIMAL, NUMERIC to `NUMBER`.
  * Strings: Convert VARCHAR, TEXT, CHAR, NVARCHAR, STRING to `VARCHAR2`.
  * Dates/Times: Convert DATETIME, TIME, DATE to `TIMESTAMP`.
  * Auto-increment & PKs: ONLY if a column is a NUMERIC Primary Key, use `NUMBER GENERATED BY DEFAULT AS IDENTITY` and set `"auto_generated": true`.

2. MSSQL (PYODBC BUG-BYPASS MODE):
  * BANNED ORACLE TYPES: NEVER output `VARCHAR2`, `NUMBER`, or `TIMESTAMP` when generating MSSQL schemas.
  * Numeric: Integers -> `INT`. Large integers -> `BIGINT`. Decimals/Numerics -> `FLOAT`.
  * Booleans: Convert BIT, BOOLEAN to `TINYINT`.
  * Strings: Convert VARCHAR, TEXT, STRING, VARCHAR2 to `NVARCHAR(255)`.
  * Dates/Times (CRITICAL PREVENT 22018/22008 ERRORS): Convert ALL date/time types (TIMESTAMP, DATETIME, DATETIME2, DATE, TIME) to `VARCHAR(50)`. NEVER output `DATETIME2` or `DATETIME`. (PyODBC fast_executemany strictly crashes when binding datetimes; storing as strings perfectly bypasses this).
  * UUIDs/GUIDs: Convert UUID/GUID to `VARCHAR(50)` and set `"auto_generated": false`. 
  * Auto-increment: You MUST physically append `IDENTITY(1,1)` to the string in the type field for INT or BIGINT Primary Keys (e.g., `"type": "BIGINT IDENTITY(1,1)"`), AND set `"auto_generated": true`.

3. STRICT FAKER-TO-SQL TYPE MATRIX (CRITICAL ERROR PREVENTION):
  You MUST assign the "faker" provider based EXACTLY on the target SQL data type.
  * If INT, BIGINT -> MUST use "random_int". (BANNED: "random_number").
  * If FLOAT -> MUST use "pyfloat". (BANNED: "random_int". Sending an integer to a FLOAT column crashes PyODBC).
  * If TINYINT -> MUST use "random_digit". 
  * If VARCHAR(50) acting as a Date/Time -> MUST use "iso8601".
  * If VARCHAR(50) acting as a UUID -> MUST use "uuid4".
  * If NVARCHAR, VARCHAR, CHAR -> MUST use a text provider ("word", "sentence", "name", "email", "company", "address").
  DO NOT add custom "args" or "values" arrays for Faker. Use the base providers only.

4. PREVENTING DML OVERFLOWS:
  * MINIMUM STRING SIZES: ALL string columns MUST be sized to at least 255. 
  * DEFAULT SIZES: If a string type lacks a size entirely, default to 255.

5. IDENTIFIER NAMING & RESERVED WORDS:
  * NO SPACES ALLOWED. Replace ANY spaces with underscores.
  * RESERVED WORDS: If a column name is a SQL reserved word (e.g., "Date", "User", "Order", "Type", "Level", "Comment", "Key"), append "_val" to it.

6. PROCEDURES, FUNCTIONS & TRIGGERS (EMBEDDED SQL):
  * You MUST generate the FULL, valid DDL statement including headers (e.g., `CREATE OR ALTER PROCEDURE...` for MSSQL).
  * DO NOT generate headless or anonymous `BEGIN...END` blocks without the CREATE header.
  * Place the generated code directly into the `"sql_body"` field of the JSON. Do NOT output a `file_path`.

7. STRICT JSON KEYS (CRITICAL PREVENT KEYERRORS):
  * You MUST use the EXACT keys shown in the EXPECTED JSON SCHEMA TEMPLATE below. 
  * For foreign_keys: You MUST use ONLY `"column"`, `"references_table"`, and `"references_column"`.
  * For indexes: You MUST use ONLY `"columns"`. 

EXPECTED JSON SCHEMA TEMPLATE:
{{
  "tables": [
    {{
      "name": "VALID_TABLE_NAME",
      "columns": [
        {{"name": "VALID_COL_NAME", "type": "DIALECT_TYPE_WITH_SIZE", "nullable": false, "auto_generated": false, "faker": "safe_faker_provider"}}
      ],
      "primary_key_columns": ["VALID_COL_NAME"],
      "indexes": [
        {{"name": "IDX_NAME", "columns": ["VALID_COL_NAME"]}}
      ],
      "foreign_keys": [
        {{"column": "LOCAL_COL", "references_table": "TARGET_TABLE", "references_column": "TARGET_COL"}}
      ]
    }}
  ],
  "procedures": [],
  "functions": [],
  "triggers": []
}}

OUTPUT FORMAT:
- Output ONLY valid JSON matching the template exactly.
- NO markdown blocks (e.g. ```json).
- NO conversational text.
"""
    def _sanitize_json_output(self, raw_str: str) -> str:
        if not raw_str:
            return "{}"
            
        # 1. Strip markdown formatting
        clean_str = re.sub(r'^```(?:json)?\s*', '', raw_str.strip(), flags=re.MULTILINE | re.IGNORECASE)
        clean_str = re.sub(r'```\s*$', '', clean_str).strip()
        
        # 2. Extract strictly the JSON object bounds
        start_idx = clean_str.find('{')
        end_idx = clean_str.rfind('}')
        
        if start_idx != -1 and end_idx != -1 and end_idx >= start_idx:
            return clean_str[start_idx:end_idx + 1]
            
        return clean_str

    def translate_to_json(self, raw_text: str) -> str:
        headers = {
            "api-subscription-key": self.api_key,
            "Content-Type": "application/json"
        }
        
        payload = {
            "model": "sarvam-105b",
            "messages": [
                {"role": "system", "content": self._get_system_prompt()},
                {"role": "user", "content": f"Translate this schema directly to JSON without any reasoning or conversational text:\n\n{raw_text}"}
            ],
            "temperature": 0.0,
            "max_tokens": 4096,
            "reasoning_effort": None  # Disables the chain-of-thought processing
        }

        max_retries = 3
        for attempt in range(max_retries):
            try:
                response = requests.post(
                    self.endpoint, 
                    headers=headers, 
                    json=payload, 
                    timeout=120  # Safe timeout limit
                )
                
                # Check for 400 Bad Request or 500 errors
                response.raise_for_status()
                response_data = response.json()
                
                # Safe JSON Extraction
                try:
                    content = response_data['choices'][0]['message']['content']
                    if not content:
                        raise ValueError("Content returned from API is None.")
                        
                    sanitized_json = self._sanitize_json_output(content)
                    
                    # Validate JSON parses correctly before returning to UI
                    json.loads(sanitized_json)
                    return sanitized_json
                    
                except (KeyError, IndexError, ValueError, json.JSONDecodeError) as e:
                    print(f"JSON Parsing failed. Raw API Response: {response_data}")
                    raise RuntimeError(f"The API returned an invalid structure. Error: {str(e)}")
                    
            except requests.exceptions.RequestException as e:
                print(f"API Request failed on attempt {attempt + 1}: {e}")
                if attempt == max_retries - 1:
                    raise
                time.sleep(2)