import requests
import json
from config import logger

class SchemaTranslator:
    def __init__(self, api_key: str):
        self.api_key = api_key
        self.endpoint = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key={self.api_key}"

    def translate_to_json(self, raw_text: str) -> str:
        """
        Calls the Sarvam API to translate raw, messy schema text into strict JSON format.
        """
        system_prompt = """
You are an expert Oracle Database Architect and data engineer.
Your task is to take messy, unstructured, raw schema definitions or pseudo-SQL and translate them into a STRICT JSON schema format.

Rules for Translation:
1. Fix typos (e.g. CustermerInfo -> CUSTOMER_INFO).
2. Map standard generic SQL types (BigInt, Smallint, Varchar) to Oracle-compliant types (NUMBER, VARCHAR2, TIMESTAMP, DATE, FLOAT).
3. Extract any Primary Keys into a table-level array called "primary_key_columns": ["col1", "col2"]. Do NOT use inline "primary_key" flags on columns.
4. Extract any indexes into a table-level array called "indexes": [{"name": "IDX_NAME", "columns": ["col1"]}].
5. Intelligently infer and assign logical Faker providers for each column based on its name.
   - For IDs: "random_int" (or if auto-generated, set "auto_generated": true)
   - For Names: "name", "first_name", or "last_name"
   - For Email: "email"
   - For Dates: "date_time", "past_datetime", or "date_between"
   - For Addresses: "address"
   - For Text/Remarks: "sentence" or "word"
6. Ensure Foreign Keys are correctly parsed into a table-level array called "foreign_keys".

Output ONLY valid JSON matching this structure. NO markdown blocks (like ```json), NO conversational text, NO explanations. Just the raw JSON object.

Example Output Structure:
{
  "tables": [
    {
      "name": "USERS",
      "columns": [
        {"name": "USER_ID", "type": "NUMBER GENERATED BY DEFAULT AS IDENTITY", "auto_generated": true},
        {"name": "USERNAME", "type": "VARCHAR2(50)", "faker": "user_name"},
        {"name": "CREATED_AT", "type": "TIMESTAMP DEFAULT CURRENT_TIMESTAMP", "faker": "past_datetime"}
      ],
      "primary_key_columns": ["USER_ID"],
      "foreign_keys": [],
      "indexes": []
    }
  ],
  "procedures": [],
  "functions": [],
  "triggers": []
}
"""
        headers = {
            "Content-Type": "application/json"
        }
        
        payload = {
            "systemInstruction": {
                "parts": [{"text": system_prompt.strip()}]
            },
            "contents": [
                {
                    "parts": [{"text": raw_text}]
                }
            ],
            "generationConfig": {
                "temperature": 0.1
            }
        }
        
        try:
            response = requests.post(self.endpoint, headers=headers, json=payload, timeout=30)
            response.raise_for_status()
            
            data = response.json()
            try:
                ai_content = data['candidates'][0]['content']['parts'][0]['text'].strip()
            except (KeyError, IndexError):
                raise ValueError("Unexpected response structure from Gemini API")
            
            # Clean up if the model accidentally included markdown blocks despite instructions
            if ai_content.startswith("```json"):
                ai_content = ai_content[7:]
            if ai_content.startswith("```"):
                ai_content = ai_content[3:]
            if ai_content.endswith("```"):
                ai_content = ai_content[:-3]
                
            return ai_content.strip()
            
        except Exception as e:
            logger.error(f"Failed to translate schema: {e}")
            if hasattr(e, 'response') and e.response is not None:
                logger.error(f"API Response: {e.response.text}")
            raise Exception(f"AI Translation failed: {e}")
