import oracledb

# Connect to the Pluggable Database (FREEPDB1)
try:
    connection = oracledb.connect(
        user="system",
        password="DevPassword123",
        dsn="localhost:1521/FREEPDB1"
    )
    print("Successfully connected to Oracle Database!")
    
    with connection.cursor() as cursor:
        # 1. Drop table if it already exists (to allow re-running the script)
        try:
            cursor.execute("DROP TABLE test_builder")
        except oracledb.DatabaseError as e:
            error, = e.args
            if error.code != 942: # 942 is "table or view does not exist"
                raise

        # 2. Create a test table
        cursor.execute("""
            CREATE TABLE test_builder (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY,
                tool_name VARCHAR2(100),
                status VARCHAR2(50),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("Table 'test_builder' created.")

        # 3. Insert a test record
        cursor.execute(
            "INSERT INTO test_builder (tool_name, status) VALUES (:1, :2)",
            ["SchemaAutoBuilder", "Development Started"]
        )
        connection.commit()
        print("Test record inserted.")

        # 4. Read it back
        cursor.execute("SELECT * FROM test_builder")
        row = cursor.fetchone()
        print(f"Retrieved from DB: {row}")

except oracledb.Error as e:
    print(f"Error connecting to Oracle: {e}")
finally:
    if 'connection' in locals():
        connection.close()