CREATE OR REPLACE TRIGGER trg_low_stock_alert
AFTER UPDATE OF STOCK_QTY ON PRODUCTS
FOR EACH ROW
WHEN (NEW.STOCK_QTY < 10)
BEGIN
    INSERT INTO INVENTORY_ALERTS (PRODUCT_ID, ALERT_MSG)
    VALUES (:NEW.PRODUCT_ID, 'CRITICAL: Stock dropped below 10 units.');
END;
/